### PR TITLE
add accordion plugin

### PR DESCRIPTION
**Pull request by goapunk**
based on https://github.com/liqd/ckeditor5-accordion/

### CODE REVIEW

**Comment by goapunk** [comment]
relies on #1

**Comment by philli-m** [comment]
@goapunk needs fixing :)

**Comment by goapunk** [comment]
@philli-m done

**Review by philli-m — COMMENTED** [review]
@goapunk it works and I can view old accordions however I cannot add new ones to information or reseults tab which normally have them?! I think the configs are mixed up?!

**Comment by goapunk** [comment]
@philli-m sorry, added the accordion to the config. And yes, the configs in general need a bit of a cleanup

**Comment by philli-m** [comment]
@goapunk now getting Reverse for 'ckeditor_upload' not found. 'ckeditor_upload' is not a valid view function or pattern name.

**Review by philli-m — APPROVED** [review]
looking good, happy to merge but just a quick question, why push package-lock.json?

**Comment by goapunk** [comment]
> looking good, happy to merge but just a quick question, why push package-lock.json?

comes from the upstream project, but seems to be quite common because it makes the installation much quicker

**Pull request merged**
